### ISSUE TITLE
yourdomain.com

### ISSUE THREAD

**Issue by danbst** [styx-static/styx#18]
I'm previewing using `latest` styx

```
styx preview --port 7000 --server-host 192.168.0.104 
```

But all links contain `yourdomain.com` as server-host. It wasn't a case for version 0.2
Can this be because I didn't upgrade my site to new theme schema?

**Comment by danbst** [comment]
No, just checked, version 0.2 runs as `yourdomain.com` too.
Only if I don't set `--server-host` I get correct 127.0.0.1 links.

**Comment by ericsagnes** [comment]
Thanks for reporting!
Fixed in https://github.com/styx-static/styx/commit/32d5beebc4fa604f3f775064d756cd9dcc6003d9.

---

Side note, the `serve` / `preview` line is a little blur, with the main difference being:
- `preview` will make `siteUrl` to be set to the server listening host and address.
- `serve` will use the `--site-url` flag value or `conf.nix` `siteUrl` value.
