### ISSUE TITLE
Theme selection mechanism

### ISSUE THREAD

**Issue by zimbatm** [styx-static/styx#23]
Hi,

is there a reason to ever have more than one theme per site?

Otherwise I would say that being able to pass a theme directory would make the configuration more composable.

Instead of having:
```nix
{
  themesDir = ./themes;
  themes = [ "my-theme" ];
}
```

You could have:
```nix
{
  theme = fetchFromGitHub { ... };
}
```

**Comment by ericsagnes** [comment]
> is there a reason to ever have more than one theme per site?

The reason is to combine themes or extend an existing theme, see  https://github.com/styx-static/styx/blob/master/src/doc/themes.adoc#combining-themes for a use case.

> Otherwise I would say that being able to pass a theme directory would make the configuration more composable.

Interesting, I commited a such [change](https://github.com/styx-static/styx/commit/163281e0c25d88e5bb3cd91889fa3b8028b98ccb) 2 days ago :)

Themes will also be added in nixpkgs so it will be possible to do something like:

```
   themes = [ styx-themes.hyde ];
```

This all will be in 0.4.0 that should be released this week.
